# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c76294d05aeed2bd0e1a0105417eaeddd29afed5b113174240fe53284468e8280117f3e89770bcd5970ec0e6b911a73b89bf72f3e34325027f940addb9abf356

test:
  secret_key_base: 1efbeb6a6f682f0064c8ad270fa894b2f99445632d3e1a9bc5d4473b3a32066604fc0c3980a8a118eb0aa8be932b3ae7ff7a1b3642e85a395d69d54eb385891a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
